name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - name: Get code
       uses: actions/checkout@v4
     - name: Install nodejs
       uses: actions/setup-node@v4
       with:
          node-version: '18'
     - name: Verify package.json exists
       run: ls -la     
     - name: Install npm
       run: npm install
     - name: Install dependencies
       run: npm ci
     - name: Run test
       run: npm test
